# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Douay Rheims Bible
email: DavidPorter65@outlook.com
description: Douay Rheims Catholic Bible original true version of 1633
url: "https://douayrheims.neocities.org"
image-path: assets/images 


# Build settings
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: new-testament
    values:
      tome: new-testament #this is used for images, because we have two OT tomes
      sidebar: NT
  - scope:
      path: new-testament/front-matter
    values:
      book: Front Matter
  - scope:
      path: new-testament/matthew
    values:
      book: Matthew
      title: The Holy Ghospel of Jesus Christ According to Matthew
  - scope:
      path: new-testament/mark
    values:
      book: Mark
      title: The Holy Ghospel of Jesus Christ According to Mark
  - scope:
      path: new-testament/luke
    values:
      book: Luke
      title: The Holy Ghospel of Jesus Christ According to Luke
  - scope:
      path: new-testament/john
    values:
      book: John
      title: The Holy Ghospel of Jesus Christ According to John
  - scope:
      path: old-testament
    values:
      sidebar: OT
  - scope:
      path: old-testament/tome-1-front
    values:
      book: Tome 1 Front
      title: THE HOLY BIBLE
      tome: old-testament-1 #this is used for images, because we have two OT tomes
  - scope:
      path: old-testament/genesis
    values:
      book: Genesis
      title: The Book of Genesis (in Hebrew Beresith)
      tome: old-testament-1 #this is used for images, because we have two OT tomes
  - scope:
      path: old-testament/micah
    values:
      book: Micah
      title: The Prophecy of Micah
      tome: old-testament-2 #this is used for images, because we have two OT tomes

